CREATE TABLE FILM (
  id_FILM SERIAL PRIMARY KEY,
  Titolo VARCHAR(100) NOT NULL,
  Genere VARCHAR(256),
  Descrizione TEXT,
  LinguaOriginale CHAR(2),
  DataRilascio DATE,
  Locandina VARCHAR(150),
  VotoMedio DECIMAL(3, 1) CHECK (VotoMedio >= 0 AND VotoMedio <= 10),
  NumeroVoti INT CHECK (NumeroVoti >= 0),
  Popularita DECIMAL(10, 2) CHECK (Popularita >= 0),
  Prezzo DECIMAL(10, 2) NOT NULL CHECK (Prezzo >= 0),
  NumeroCopieDisponibili SMALLINT NOT NULL CHECK (NumeroCopieDisponibili >= 0),
  NumeroCopieInPrestito SMALLINT NOT NULL DEFAULT 0 CHECK (NumeroCopieInPrestito >= 0),
  Stato VARCHAR(20) DEFAULT 'disponibile'
);

CREATE INDEX idx_titolo ON FILM (Titolo);
CREATE INDEX idx_genere ON FILM (Genere);

CREATE TABLE UTENTE (
  id_UTENTE SERIAL PRIMARY KEY,
  Username VARCHAR(20) UNIQUE NOT NULL,
  Password VARCHAR(100) NOT NULL,
  max_rentals INT DEFAULT 5
);

CREATE TABLE NOLEGGIO (
  id_NOLEGGIO SERIAL PRIMARY KEY,
  id_UTENTE INT NOT NULL,
  id_FILM INT NOT NULL,
  NumeroCopieNoleggiate INT NOT NULL CHECK (NumeroCopieNoleggiate > 0),
  DataNoleggio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DataRestituzione TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 month',
  Restituito BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (id_UTENTE) REFERENCES UTENTE(id_UTENTE) ON DELETE CASCADE,
  FOREIGN KEY (id_FILM) REFERENCES FILM(id_FILM) ON DELETE CASCADE
);

CREATE INDEX idx_id_film ON NOLEGGIO (id_FILM);
CREATE INDEX idx_id_utente ON NOLEGGIO (id_UTENTE);

CREATE TABLE NOTIFICA (
  id_NOTIFICA SERIAL PRIMARY KEY,
  id_UTENTE INT NOT NULL,
  Messaggio TEXT NOT NULL,
  DataNotifica TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Stato VARCHAR(20) DEFAULT 'inviata',
  FOREIGN KEY (id_UTENTE) REFERENCES UTENTE(id_UTENTE) ON DELETE CASCADE
);