@startuml CreaOrdine-SD
actor Utente
participant CarrelloFrame
participant Controller
participant Ordine
participant OrdiniJDBC
participant ProdottoJDBC
participant Articoli
participant ArticoliJDBC
participant TesseraJDBC

Utente -> CarrelloFrame : creaOrdine()
activate CarrelloFrame
CarrelloFrame -> CarrelloFrame : verificaDatiCarrello()
alt Errore dati
    CarrelloFrame -> CarrelloFrame : mostraErrore()
    deactivate CarrelloFrame
else Dati ok
    CarrelloFrame -> CarrelloFrame : calcolaTotale()
    CarrelloFrame -> Controller : nuovoOrdine()
    deactivate CarrelloFrame
    activate Controller
    create Ordine
    Controller -> Ordine : crea()
    activate Ordine
    Ordine --> Controller
    deactivate Ordine
    Controller -> OrdiniJDBC : salvaOrdine()
    activate OrdiniJDBC
    OrdiniJDBC --> Controller
    deactivate OrdiniJDBC
    Controller -> Controller : aggiornaModelloOrdine()
    Controller -> Controller : controlliInterni()
    Controller -> Controller : creaRowData()
    Controller --> CarrelloFrame : confermaCreazioneOrdine
    deactivate Controller
    activate CarrelloFrame
    CarrelloFrame -> CarrelloFrame : mostraConfermaCreazione()
    CarrelloFrame -> Controller : aggiornaScorte()
    activate Controller
    Controller -> ProdottoJDBC : updateScorte()
    activate ProdottoJDBC
    ProdottoJDBC --> Controller
    deactivate ProdottoJDBC
    Controller --> CarrelloFrame
    deactivate Controller
    CarrelloFrame -> Controller : aggiungiArticoli()
    activate Controller
    create Articoli
    Controller -> Articoli : crea()
    activate Articoli
    Articoli --> Controller
    deactivate Articoli
    Controller -> ArticoliJDBC : salvaArticoliOrdine()
    activate ArticoliJDBC
    ArticoliJDBC --> Controller
    deactivate ArticoliJDBC
    Controller --> CarrelloFrame
    deactivate Controller
    CarrelloFrame -> Controller : aggiornaPunti()
    activate Controller
    Controller -> TesseraJDBC : updatePunti()
    activate TesseraJDBC
    TesseraJDBC --> Controller
    deactivate TesseraJDBC
    Controller --> CarrelloFrame
    deactivate Controller
    CarrelloFrame -> CarrelloFrame : pulisciCarrello()
end
deactivate CarrelloFrame

@enduml