@startuml CreaOrdine-SD

participant Actor
Actor -> CarrelloFrame : creaOrdine
activate CarrelloFrame
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : findClientId
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : calcolaTotale
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> Controller : nuovoordine
activate Controller
create Ordine
Controller -> Ordine : new
activate Ordine
Ordine --> Controller
deactivate Ordine
Controller -> OrdiniJDBC : newordine
activate OrdiniJDBC
OrdiniJDBC --> Controller
deactivate OrdiniJDBC
Controller -> Controller : updateOrdineModelAfterInsert
activate Controller
Controller -> Controller : x ->
activate Controller
Controller -> Controller : x ->
activate Controller
Controller --> Controller
deactivate Controller
Controller --> Controller
deactivate Controller
Controller -> Controller : checkNull
activate Controller
Controller --> Controller
deactivate Controller
Controller -> Controller : checkNull
activate Controller
Controller --> Controller
deactivate Controller
Controller -> Controller : createRowData
activate Controller
Controller -> Controller : checkNull
activate Controller
Controller --> Controller
deactivate Controller
Controller --> Controller
deactivate Controller
Controller --> Controller
deactivate Controller
Controller --> CarrelloFrame
deactivate Controller
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> Controller : CurrOrd
activate Controller
Controller --> CarrelloFrame
deactivate Controller
CarrelloFrame -> CarrelloFrame : processArticoli
activate CarrelloFrame
CarrelloFrame -> Controller : upscorte
activate Controller
Controller -> ProdottoJDBC : updateScorte
activate ProdottoJDBC
ProdottoJDBC --> Controller
deactivate ProdottoJDBC
Controller --> CarrelloFrame
deactivate Controller
CarrelloFrame -> Controller : newarticoli
activate Controller
create Articoli
Controller -> Articoli : new
activate Articoli
Articoli --> Controller
deactivate Articoli
Controller -> ArticoliJDBC : newordine
activate ArticoliJDBC
ArticoliJDBC --> Controller
deactivate ArticoliJDBC
Controller --> CarrelloFrame
deactivate Controller
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : assegnaPunti
activate CarrelloFrame
CarrelloFrame -> Controller : uppunti
activate Controller
Controller -> TesseraJDBC : updatepunti
activate TesseraJDBC
TesseraJDBC --> Controller
deactivate TesseraJDBC
Controller --> CarrelloFrame
deactivate Controller
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : clean
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
CarrelloFrame -> CarrelloFrame : showError
activate CarrelloFrame
CarrelloFrame --> CarrelloFrame
deactivate CarrelloFrame
return
@enduml