@startuml NuovoCliente-SD
actor Utente
participant NuovoClienteFrame
participant Controller
participant ClienteJDBC
participant TesseraJDBC

Utente -> NuovoClienteFrame : inserisce dati cliente
activate NuovoClienteFrame
NuovoClienteFrame -> NuovoClienteFrame : validateFields()
alt Campi non validi
    NuovoClienteFrame -> NuovoClienteFrame : mostraErroreValidazione()
    deactivate NuovoClienteFrame
else Campi validi
    NuovoClienteFrame -> Controller : newclt(...)
    deactivate NuovoClienteFrame
    activate Controller
    Controller -> ClienteJDBC : setNewCt(cliente)
    activate ClienteJDBC
    ClienteJDBC --> Controller : esito
    deactivate ClienteJDBC
    alt Cliente creato
        Controller -> Controller : updateClienteModelAfterInsert(...)
        Controller -> ClienteJDBC : getIdCt(codFis)
        activate ClienteJDBC
        ClienteJDBC --> Controller : codClienteDb
        deactivate ClienteJDBC
        Controller -> TesseraJDBC : newtessera(codClienteDb)
        activate TesseraJDBC
        TesseraJDBC --> Controller : esito
        deactivate TesseraJDBC
    end
    Controller --> NuovoClienteFrame : conferma creazione
    deactivate Controller
    activate NuovoClienteFrame
    NuovoClienteFrame -> NuovoClienteFrame : clean()
    deactivate NuovoClienteFrame
end

@enduml