package HashTable;

public class Esercizio2 {

    public static void main(String[] args) {
    }

    public void autoGeneratedMethodStub() {
        // Implementazione del metodo
        System.out.println("Metodo auto-generato eseguito.");
    }
}
